USD_NOTIFY_USER_ID = '@test2020_echo_bot'
TG_TOKEN = '1177786376:AAFQn7uZX8zdcdKDtF1gmEcxCR64DpG_Jb0'
URL_USD = 'https://kurs.com.ua/'
URL_EURO = 'https://kurs.com.ua/valyuta/eur'
URL_BTC = 'https://coinmarketcap.com/currencies/bitcoin/'
URL_WEATHER = 'https://sinoptik.ua/погода-одесса'
