USD_NOTIFY_USER_ID = '@test_echo_bot'
TG_TOKEN = '111777...:AAFQn7uZX8zdcdtF1gmEcx...'
URL_USD = 'https://kurs.com.ua/'
URL_EURO = 'https://kurs.com.ua/valyuta/eur'
URL_BTC = 'https://coinmarketcap.com/currencies/bitcoin/'
URL_WEATHER = 'https://sinoptik.ua/погода-одесса'
