USD_NOTIFY_USER_ID = '@test_echo_bot'
TG_TOKEN = '11777863:AAFQn7uZX8zdcdKDtF1gmEcx...'
URL_USD = 'https://kurs.com.ua/'
URL_EURO = 'https://kurs.com.ua/valyuta/eur'
URL_BTC = 'https://coinmarketcap.com/currencies/bitcoin/'
URL_WEATHER = 'https://sinoptik.ua/погода-одесса'
